name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Build React
        run: |
          pnpm install
          pnpm build

      - name: Archive React build
        run: tar -czf react-build.tar.gz dist

      - name: Transfer files to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: |
            react-build.tar.gz
          target: /opt/frontend

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /opt/frontend
            tar -xzf /opt/frontend/react-build.tar.gz -C /opt/frontend
            docker cp /opt/frontend/dist nginx:/usr/share/nginx/html
            docker exec nginx nginx -s reload
