name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t anifox .

      - name: Save Docker image as tar
        run: docker save anifox -o app.tar

      - name: Add permission for tar
        run: chmod 664 app.tar

      - name: Transfer files to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ./app.tar
          target: /opt/frontend

      - name: SSH into remote server and run Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /opt/frontend
            docker container stop anifox
            docker container rm anifox
            docker rmi anifox
            docker load -i app.tar
            docker run -d --network anifox-network -p 8000:8000 --log-opt max-size=50m --name anifox anifox
